; ORION-6 PRO — pont USB ↔ CAN mode MIT (Teensy 4.1)
; Compilation : pio run -e teensy41        Téléversement : pio run -e teensy41 -t upload
[platformio]
default_envs = teensy41
src_dir = src

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
board_build.f_cpu = 600000000L
build_flags = -O2 -Wall -DUSB_SERIAL
monitor_speed = 115200
